/**
 * js/spots-data.js - single source of truth for all climbing spots.
 *
 * UMD: a browser classic <script> exposes window.SPOTS_DATA; Node import gets
 * the same object via module.exports (default import).
 *
 * Each spot keeps `diff` (the original raw difficulty display string, verbatim
 * from the old inline data) plus a structured `grades` object used for
 * filtering/validation. Spots without a structured difficulty (e.g.
 * "Top Rope/Lead") have grades: null and `diff` remains their display text.
 */
(function (root, factory) {
  if (typeof module === 'object' && module && module.exports) {
    module.exports = factory();
  } else {
    root.SPOTS_DATA = factory();
  }
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  var spots = [
    // --- Outdoor bouldering (NB) ---
    { id: 1, typeCode: 'NB', lat: 22.213, lng: 114.200, diff: "VB - V12", grades: { boulder: { min: "VB", max: "V12" } }, name: { zh: "舂坎角", en: "Chung Hom Kok" }, desc: { zh: "約97條路線，花崗岩。路況包括手足並用的攀爬石壁。", en: "Around 97 routes on granite. Includes scrambling sections." }, trans: { zh: "中環乘6X等巴士至舂坎角道", en: "Bus 6X from Central to Chung Hom Kok Rd" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.213,114.200", source: "https://hongkongclimbing.com/routes/hong-kong/chung-hom-kok-boulders/" },
    { id: 2, typeCode: 'NB', lat: 22.228, lng: 114.251, diff: "VB - V12+", grades: { boulder: { min: "VB", max: "V12+" } }, name: { zh: "石澳 - 抱石區", en: "Shek O - Bouldering" }, desc: { zh: "約143條路線。大頭洲「九宮格」是馳名攀石地。", en: "143 routes. Tai Tau Chau is famous for its intricate rock textures." }, trans: { zh: "筲箕灣乘9號巴士", en: "Bus 9 from Shau Kei Wan" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.228,114.251", source: "https://www.thecrag.com/en/climbing/hong-kong/hong-kong-island/area/12484819" },
    { id: 3, typeCode: 'NB', lat: 22.245, lng: 114.290, diff: "VB - V12", grades: { boulder: { min: "VB", max: "V12" } }, name: { zh: "東龍洲 - 抱石", en: "Tung Lung Chau - Boulder" }, desc: { zh: "東海岸佈滿懸崖峭壁，表面粗糙，摩擦力極佳。", en: "East coast cliffs with excellent rough friction." }, trans: { zh: "西灣河/三家村乘街渡", en: "Ferry from Sai Wan Ho / Sam Ka Tsuen" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.245,114.290", source: "https://hongkongclimbing.com/blocs/tung-lung-bouldering/" },
    { id: 4, typeCode: 'NB', lat: 22.200, lng: 114.130, diff: "VB - V10", grades: { boulder: { min: "VB", max: "V10" } }, name: { zh: "南丫島", en: "Lamma Island" }, desc: { zh: "山地塘一帶有多處天然抱石，如月老石等。", en: "Multiple natural boulders around Mount Stenhouse." }, trans: { zh: "中環4號碼頭乘渡輪", en: "Ferry from Central Pier 4" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.200,114.130", source: "https://hongkongclimbing.com/routes/lamma/lamma-boulders/" },

    // --- Gym bouldering (AB) ---
    { id: 5, typeCode: 'AB', lat: 22.335, lng: 114.198, diff: "V0 - V10", grades: { boulder: { min: "V0", max: "V10" } }, name: { zh: "JUST CLIMB (新蒲崗店)", en: "JUST CLIMB (San Po Kong)" }, desc: { zh: "超過100條路線，分4大程度12級難度。", en: "Over 100 routes divided into 12 difficulty levels." }, trans: { zh: "新蒲崗", en: "San Po Kong" }, address: { zh: "香港九龍新蒲崗太子道東706號地下D室", en: "Room D, G/F, 706 Prince Edward Road East, San Po Kong, Kowloon, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.335,114.198", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 6, typeCode: 'AB', lat: 22.292, lng: 114.207, diff: "V0 - V7", grades: { boulder: { min: "V0", max: "V7" } }, name: { zh: "Verm City (鰂魚涌)", en: "Verm City (Quarry Bay)" }, desc: { zh: "香港最大抱石場地逾1.8萬呎，設4.5米高牆。", en: "HK's largest gym (18k sq.ft) with 4.5m walls." }, trans: { zh: "鰂魚涌渣華道", en: "Java Road, Quarry Bay" }, address: { zh: "香港鰂魚涌渣華道321號柯達大廈4樓", en: "4/F, Kodak House, 321 Java Road, Quarry Bay, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.292,114.207", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 7, typeCode: 'AB', lat: 22.385, lng: 114.199, diff: "V0 - V7+", grades: { boulder: { min: "V0", max: "V7+" } }, name: { zh: "HK Climbing Park (沙田)", en: "HK Climbing Park (Shatin)" }, desc: { zh: "高達4.5米的室內抱石區域，多達50條抱石路線。", en: "4.5m tall walls with up to 50 bouldering routes." }, trans: { zh: "沙田富豪花園", en: "Belair Gardens, Shatin" }, address: { zh: "香港新界沙田大涌橋路52號富豪花園商場2期2樓", en: "Level 2, Belair Gardens Shopping Arcade Phase 2, 52 Tai Chung Kiu Road, Sha Tin, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.385,114.199", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 8, typeCode: 'AB', lat: 22.322, lng: 114.168, diff: "V0 - V7", grades: { boulder: { min: "V0", max: "V7" } }, name: { zh: "尚山岩館 (深水埗)", en: "Crux (Sham Shui Po)" }, desc: { zh: "以動物主題分級，設有人氣訓練板Moonboard。", en: "Animal-themed grading, features a Moonboard." }, trans: { zh: "深水埗大南街", en: "Tai Nan Street, Sham Shui Po" }, address: { zh: "香港九龍太子荔枝角道33號百匯軒1樓", en: "1/F, Cite 33, 33 Lai Chi Kok Road, Prince Edward, Kowloon, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.322,114.168", source: "https://hongkongclimbing.com/climbing-walls/" },

    // --- Outdoor climbing (NC) ---
    { id: 9, typeCode: 'NC', lat: 22.230, lng: 114.250, diff: "F4 - F8A+", grades: { rope: { min: "F4", max: "F8A+" } }, name: { zh: "石澳 - 運動攀登", en: "Shek O - Sport Climbing" }, desc: { zh: "包含日落隙及技術牆，考驗力量與平衡。", en: "Includes Sunset Crack and Tech Wall, testing power & balance." }, trans: { zh: "筲箕灣乘9號巴士", en: "Bus 9 from Shau Kei Wan" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.230,114.250", source: "https://hongkongclimbing.com/routes/hong-kong/shek-o/" },
    { id: 10, typeCode: 'NC', lat: 22.247, lng: 114.288, diff: "F4 - F8A+", grades: { rope: { min: "F4", max: "F8A+" } }, name: { zh: "東龍洲 - 攀登", en: "Tung Lung Chau - Climbing" }, desc: { zh: "崖下海浪咆哮，極具挑戰性的海溝及巨牆。", en: "Challenging sea cliff walls and gullies above crashing waves." }, trans: { zh: "乘街渡前往", en: "Ferry from Sai Wan Ho" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.247,114.288", source: "https://www.thecrag.com/en/climbing/hong-kong/tung-lung-chau" },
    { id: 11, typeCode: 'NC', lat: 22.345, lng: 114.165, diff: "F2B - F8B", grades: { rope: { min: "F2B", max: "F8B" } }, name: { zh: "畢架山", en: "Beacon Hill" }, desc: { zh: "花崗岩表面粗糙，擁有超過60條路線。", en: "Rough granite surface with over 60 routes." }, trans: { zh: "石硤尾轉乘32M小巴", en: "Minibus 32M from Shek Kip Mei" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.345,114.165", source: "https://www.thecrag.com/en/climbing/hong-kong/kowloon/area/825492426" },
    { id: 12, typeCode: 'NC', lat: 22.352, lng: 114.185, diff: "F5 - F7C+", grades: { rope: { min: "F5", max: "F7C+" } }, name: { zh: "獅子山", en: "Lion Rock" }, desc: { zh: "經典多繩距路線「鬼佬」是必爬路線，可俯瞰維港。", en: "Classic multi-pitch 'Gweilo' overlooking Victoria Harbour." }, trans: { zh: "慈雲山徒步上山", en: "Hike up from Tsz Wan Shan" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.352,114.185", source: "https://www.thecrag.com/12484579" },
    { id: 13, typeCode: 'NC', lat: 22.272, lng: 114.155, diff: "F4 - F7B", grades: { rope: { min: "F4", max: "F7B" } }, name: { zh: "中環岩壁", en: "Central Crags" }, desc: { zh: "約109條路線，在摩天大廈簇擁下享受攀岩。", en: "Around 109 routes nestled among skyscrapers." }, trans: { zh: "半山區", en: "Mid-Levels" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.272,114.155", source: "https://hongkongclimbing.com/routes/hong-kong/central-crags/" },

    // --- Gym climbing (AC) ---
    { id: 14, typeCode: 'AC', lat: 22.324, lng: 114.198, diff: "Top Rope/Lead", grades: null, name: { zh: "JUST CLIMB (啟德)", en: "JUST CLIMB (Kai Tak)" }, desc: { zh: "全港唯一有蓋綜合攀石場。17.5米先鋒牆。", en: "HK's only covered complex. 17.5m lead wall." }, trans: { zh: "啟德體育大道", en: "Kai Tak Sports Avenue" }, address: { zh: "香港九龍城啟德體育園啟德體育大道（啟德體藝館外）攀岩牆", en: "Kai Tak Sports Park, Kai Tak Sports Avenue (climbing wall outside Kai Tak Arena), Kai Tak, Kowloon, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.324,114.198", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 15, typeCode: 'AC', lat: 22.322, lng: 114.163, diff: "Top Rope", grades: null, name: { zh: "大角咀體育館", en: "Tai Kok Tsui Sports Centre" }, desc: { zh: "共設10條路線(高9米)。需持二級運動攀登證書。", en: "10 routes (9m). Level 2 climbing cert required." }, trans: { zh: "大角咀福全街", en: "Fuk Tsun Street, Tai Kok Tsui" }, address: { zh: "香港九龍大角咀福全街63號大角咀市政大廈5至7樓", en: "5/F-7/F, Tai Kok Tsui Municipal Services Building, 63 Fuk Tsun Street, Tai Kok Tsui, Kowloon, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.322,114.163", source: "https://www.lcsd.gov.hk/clpss/tc/webApp/Facility/Details.do?fid=536" },

    // --- Outdoor bouldering (NB) - new additions ---
    { id: 16, typeCode: 'NB', lat: 22.214, lng: 114.214, diff: "V0 - V7", grades: { boulder: { min: "V0", max: "V7" } }, name: { zh: "赤柱抱石", en: "Stanley Blocs" }, desc: { zh: "赤柱一帶的花崗岩抱石區，多條路線散佈於山徑旁。", en: "Granite boulders scattered along trails near Stanley." }, trans: { zh: "中環乘巴士至赤柱", en: "Bus from Central to Stanley" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.214,114.214", source: "https://hongkongclimbing.com/blocs/stanley/" },
    { id: 17, typeCode: 'NB', lat: 22.405, lng: 114.123, diff: "V0 - V10", grades: { boulder: { min: "V0", max: "V10" } }, name: { zh: "大帽山抱石", en: "Tai Mo Shan Boulders" }, desc: { zh: "香港最高峰大帽山一帶的花崗岩抱石，路線分佈廣闊。", en: "Granite bouldering around Tai Mo Shan, Hong Kong's highest peak." }, trans: { zh: "荃灣乘巴士至大帽山郊野公園", en: "Bus from Tsuen Wan to Tai Mo Shan Country Park" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.405,114.123", source: "https://www.thecrag.com/en/climbing/hong-kong/new-territories/area/3808678353" },
    { id: 18, typeCode: 'NB', lat: 22.380, lng: 114.105, diff: "V0 - V9", grades: { boulder: { min: "V0", max: "V9" } }, name: { zh: "荃灣抱石", en: "Tsuen Wan Boulders" }, desc: { zh: "荃灣周邊多個花崗岩抱石點，包括下花山與蓮花山一帶。", en: "Several granite bouldering sectors around Tsuen Wan, including Ha Fa Shan and Lin Fa Shan." }, trans: { zh: "荃灣乘小巴上山", en: "Minibus from Tsuen Wan uphill" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.380,114.105", source: "https://www.thecrag.com/en/climbing/hong-kong/tsuen-wan-boulders" },
    { id: 19, typeCode: 'NB', lat: 22.312, lng: 114.266, diff: "V0 - V8", grades: { boulder: { min: "V0", max: "V8" } }, name: { zh: "銀線灣抱石", en: "Silver Bay Blocs" }, desc: { zh: "清水灣半島銀線灣一帶的海邊抱石，岩石粗糙。", en: "Rough seaside boulders near Silver Bay on Clear Water Bay Peninsula." }, trans: { zh: "坑口乘巴士至銀線灣", en: "Bus from Hang Hau to Silver Bay" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.312,114.266", source: "https://hongkongclimbing.com/silver-bay-blocs/" },
    { id: 20, typeCode: 'NB', lat: 22.200, lng: 114.030, diff: "V0 - V6", grades: { boulder: { min: "V0", max: "V6" } }, name: { zh: "長洲抱石", en: "Cheung Chau Blocs" }, desc: { zh: "長洲島上的花崗岩抱石區，路線多沿海邊散佈。", en: "Granite bouldering scattered around the coast of Cheung Chau island." }, trans: { zh: "中環碼頭乘渡輪至長洲", en: "Ferry from Central Pier to Cheung Chau" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.200,114.030", source: "https://hongkongclimbing.com/cheung-chau/" },
    { id: 21, typeCode: 'NB', lat: 22.410, lng: 114.240, diff: "V0 - V8", grades: { boulder: { min: "V0", max: "V8" } }, name: { zh: "馬鞍山抱石", en: "Ma On Shan Bouldering" }, desc: { zh: "馬鞍山一帶的天然抱石區，岩石質地良好。", en: "Natural bouldering sectors around Ma On Shan with good rock quality." }, trans: { zh: "馬鞍山乘巴士或徒步", en: "Bus or hike from Ma On Shan" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.410,114.240", source: "https://hongkongclimbing.com/blocs/ma-on-shan-bouldering/" },

    // --- Outdoor climbing (NC) - new additions ---
    { id: 22, typeCode: 'NC', lat: 22.256, lng: 114.250, diff: "F5A - F7B", grades: { rope: { min: "F5A", max: "F7B" } }, name: { zh: "哥連臣角", en: "Cape Collinson" }, desc: { zh: "港島東南端的海崖攀登區，以傳統攀登路線為主。", en: "Sea cliff climbing at the southeastern tip of Hong Kong Island, mostly trad routes." }, trans: { zh: "柴灣乘小巴至哥連臣角", en: "Minibus from Chai Wan to Cape Collinson" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.256,114.250", source: "https://www.thecrag.com/en/climbing/hong-kong/hong-kong-island/area/12484963" },
    { id: 23, typeCode: 'NC', lat: 22.295, lng: 114.244, diff: "F5A - F7A", grades: { rope: { min: "F5A", max: "F7A" } }, name: { zh: "魔鬼山", en: "Devil's Peak" }, desc: { zh: "九龍東魔鬼山的岩壁，俯瞰鯉魚門海峽。", en: "Crags on Devil's Peak overlooking Lei Yue Mun channel." }, trans: { zh: "油塘徒步上山", en: "Hike up from Yau Tong" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.295,114.244", source: "https://www.thecrag.com/en/climbing/hong-kong/kowloon/area/12484627" },
    { id: 24, typeCode: 'NC', lat: 22.267, lng: 114.219, diff: "F5A - F7B", grades: { rope: { min: "F5A", max: "F7B" } }, name: { zh: "柏架山", en: "Mount Parker Crags" }, desc: { zh: "柏架山一帶的多處岩壁，路線以運動攀登為主。", en: "Multiple crags around Mount Parker, mostly sport climbing." }, trans: { zh: "鰂魚涌徒步上山", en: "Hike up from Quarry Bay" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.267,114.219", source: "https://www.thecrag.com/en/climbing/hong-kong/hong-kong-island/area/2981853918" },
    { id: 25, typeCode: 'NC', lat: 22.290, lng: 114.290, diff: "F4 - F7B", grades: { rope: { min: "F4", max: "F7B" } }, name: { zh: "清水灣", en: "Clear Water Bay" }, desc: { zh: "清水灣半島的海崖與岩壁攀登區。", en: "Sea cliffs and crags on Clear Water Bay Peninsula." }, trans: { zh: "坑口乘巴士至清水灣", en: "Bus from Hang Hau to Clear Water Bay" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.290,114.290", source: "https://hongkongclimbing.com/routes/new-territories/clear-water-bay/" },
    { id: 26, typeCode: 'NC', lat: 22.240, lng: 114.148, diff: "F4 - F7A", grades: { rope: { min: "F4", max: "F7A" } }, name: { zh: "鴨脷洲", en: "Ap Lei Chau" }, desc: { zh: "鴨脷洲島上的岩壁攀登區，交通便利。", en: "Crags on Ap Lei Chau island with easy access." }, trans: { zh: "港鐵利東站步行", en: "MTR to Lei Tung station, then walk" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.240,114.148", source: "https://hongkongclimbing.com/routes/hong-kong/ap-lei-chau/ap-lei-chau-crags/" },
    { id: 27, typeCode: 'NC', lat: 22.344, lng: 114.219, diff: "F4 - F8A", grades: { rope: { min: "F4", max: "F8A" } }, name: { zh: "飛鵝山", en: "Kowloon Peak (Fei Ngo Shan)" }, desc: { zh: "飛鵝山的岩壁與抱石區，俯瞰九龍與港島。", en: "Crags and boulders on Fei Ngo Shan overlooking Kowloon and the island." }, trans: { zh: "彩虹乘小巴上山", en: "Minibus from Choi Hung uphill" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.344,114.219", source: "https://www.thecrag.com/en/climbing/hong-kong/kowloon/area/12484603" },
    { id: 28, typeCode: 'NC', lat: 22.167, lng: 114.260, diff: "F5A - F7B", grades: { rope: { min: "F5A", max: "F7B" } }, name: { zh: "蒲台島", en: "Po Toi" }, desc: { zh: "蒲台島的花崗岩海崖攀登區，位處香港南端。", en: "Granite sea cliff climbing on Po Toi, one of Hong Kong's southernmost spots." }, trans: { zh: "香港仔或赤柱乘街渡", en: "Ferry from Aberdeen or Stanley" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.167,114.260", source: "https://hongkongclimbing.com/routes/po-toi/" },
    { id: 29, typeCode: 'NC', lat: 22.207, lng: 114.256, diff: "F5A - F7A", grades: { rope: { min: "F5A", max: "F7A" } }, name: { zh: "鶴咀海崖", en: "Cape D'Aguilar" }, desc: { zh: "鶴咀半島東南端的海崖攀登區。", en: "Sea cliff climbing at the southeastern tip of Cape D'Aguilar." }, trans: { zh: "石澳乘巴士至鶴咀", en: "Bus from Shek O to Cape D'Aguilar" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.207,114.256", source: "https://hongkongclimbing.com/cape-daguilar/" },

    // --- Gym bouldering (AB) - new additions ---
    { id: 30, typeCode: 'AB', lat: 22.249, lng: 114.169, diff: "N/A", grades: null, name: { zh: "Attic V 攀石中心 (黃竹坑)", en: "Attic V (Wong Chuk Hang)" }, desc: { zh: "黃竹坑的室內抱石館。", en: "Indoor bouldering gym in Wong Chuk Hang." }, trans: { zh: "港鐵黃竹坑站", en: "MTR Wong Chuk Hang station" }, address: { zh: "香港黃竹坑道49號得力工業大廈地下E舖", en: "Shop E, G/F, Derrick Industrial Building, 49 Wong Chuk Hang Road, Wong Chuk Hang, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.249,114.169", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 31, typeCode: 'AB', lat: 22.383, lng: 114.206, diff: "N/A", grades: null, name: { zh: "Camp Four Bouldering (沙田)", en: "Camp Four Bouldering (Shatin)" }, desc: { zh: "沙田的室內抱石館。", en: "Indoor bouldering gym in Shatin." }, trans: { zh: "沙田", en: "Shatin" }, address: { zh: "香港新界沙田源順圍2號冠華鏡廠集團大廈3樓305室", en: "Room 305, 3/F, Koon Wah Mirror Group Building, 2 Yuen Shun Circuit, Sha Tin, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.383,114.206", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 32, typeCode: 'AB', lat: 22.324, lng: 114.210, diff: "N/A", grades: null, name: { zh: "Project Climb & Boulder (九龍灣)", en: "Project Climb & Boulder (Kowloon Bay)" }, desc: { zh: "九龍灣的室內抱石館。", en: "Indoor bouldering gym in Kowloon Bay." }, trans: { zh: "九龍灣", en: "Kowloon Bay" }, address: { zh: "九龍灣臨興街32號美羅中心1期2樓11室", en: "Room 11, 2/F, Metro Centre Phase 1, 32 Lam Hing Street, Kowloon Bay, Kowloon, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.324,114.210", source: "https://hongkongclimbing.com/climbing-walls/" },

    // --- Gym climbing (AC) - new additions ---
    { id: 33, typeCode: 'AC', lat: 22.308, lng: 114.175, diff: "Top Rope/Lead", grades: null, name: { zh: "YMCA Kings Park 攀石牆", en: "YMCA Kings Park Climbing Wall" }, desc: { zh: "京士柏青年會的高牆，設先鋒攀登牆。", en: "Tall walls at YMCA Kings Park with lead climbing." }, trans: { zh: "港鐵佐敦站", en: "MTR Jordan station" }, address: { zh: "九龍油麻地加士居道22號香港基督教青年會京士柏百周年紀念中心攀石牆", en: "YMCA King's Park Centenary Centre, 22 Gascoigne Road, Yau Ma Tei, Kowloon, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.308,114.175", source: "https://hongkongclimbing.com/climbing-walls/" },
    // --- Gym bouldering (AB) - additional gyms (catalog completion) ---
    { id: 34, typeCode: 'AB', lat: 22.356, lng: 114.125, diff: "N/A", grades: null, name: { zh: "Butterfly Climbing Gym (葵涌)", en: "Butterfly Climbing Gym (Kwai Chung)" }, desc: { zh: "葵涌的室內抱石館。", en: "Indoor bouldering gym in Kwai Chung." }, trans: { zh: "葵涌", en: "Kwai Chung" }, address: { zh: "葵涌葵芳葵豐街38-42號Magnet Place第2期14A室", en: "Unit 14A, Tower 2, Magnet Place, 38-42 Kwai Fung Crescent, Kwai Fong, Kwai Chung, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.356,114.125", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 35, typeCode: 'AB', lat: 22.323, lng: 114.163, diff: "N/A", grades: null, name: { zh: "Mizu Climbing (大角咀)", en: "Mizu Climbing (Tai Kok Tsui)" }, desc: { zh: "大角咀的室內抱石館。", en: "Indoor bouldering gym in Tai Kok Tsui." }, trans: { zh: "大角咀", en: "Tai Kok Tsui" }, address: { zh: "大角咀合桃街9號2樓", en: "2/F, 9 Walnut Street, Tai Kok Tsui, Kowloon, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.323,114.163", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 36, typeCode: 'AB', lat: 22.341, lng: 114.136, diff: "N/A", grades: null, name: { zh: "The Player (荔枝角)", en: "The Player (Lai Chi Kok)" }, desc: { zh: "荔枝角的室內抱石館。", en: "Indoor bouldering gym in Lai Chi Kok." }, trans: { zh: "荔枝角", en: "Lai Chi Kok" }, address: { zh: "荔枝角荔景山路272號荔灣花園上層地下6B及6B1號舖", en: "Shop 6B & 6B1, Upper Ground Floor, Lai Chi Kok Bay Garden, 272 Lai King Hill Road, Lai Chi Kok, Kowloon, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.341,114.136", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 37, typeCode: 'AB', lat: 22.313, lng: 114.187, diff: "N/A", grades: null, name: { zh: "Tanuki Bouldering (紅磡)", en: "Tanuki Bouldering (Hung Hom)" }, desc: { zh: "紅磡的室內抱石館。", en: "Indoor bouldering gym in Hung Hom." }, trans: { zh: "紅磡", en: "Hung Hom" }, address: { zh: "九龍土瓜灣馬頭圍道200號地下A及B舖", en: "Shop A & B, G/F, 200 Ma Tau Wai Road, To Kwa Wan, Kowloon, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.313,114.187", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 38, typeCode: 'AB', lat: 22.308, lng: 114.169, diff: "N/A", grades: null, name: { zh: "Campus Climbing HK (佐敦)", en: "Campus Climbing HK (Jordan)" }, desc: { zh: "佐敦的室內抱石館。", en: "Indoor bouldering gym in Jordan." }, trans: { zh: "佐敦", en: "Jordan" }, address: { zh: "佐敦廣東道600號1樓", en: "1/F, 600 Canton Road, Jordan, Kowloon, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.308,114.169", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 39, typeCode: 'AB', lat: 22.287, lng: 114.150, diff: "N/A", grades: null, name: { zh: "Keep Climbing (上環)", en: "Keep Climbing (Sheung Wan)" }, desc: { zh: "上環的室內抱石館。", en: "Indoor bouldering gym in Sheung Wan." }, trans: { zh: "上環", en: "Sheung Wan" }, address: { zh: "上環干諾道西28號威勝商業大廈2樓6室", en: "Room 6, 2/F, Wayson Commercial Building, 28 Connaught Road West, Sheung Wan, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.287,114.150", source: "https://hongkongclimbing.com/climbing-walls/" },
    // --- Outdoor bouldering (NB) - catalog completion ---
    { id: 40, typeCode: 'NB', lat: 22.285, lng: 114.221, diff: "V0 - V6", grades: { boulder: { min: "V0", max: "V6" } }, name: { zh: "太古抱石", en: "Tai Koo Boulders" }, desc: { zh: "太古一帶的花崗岩抱石區，路線散佈於山徑旁。", en: "Granite boulders scattered along trails near Tai Koo." }, trans: { zh: "港鐵太古站步行上山", en: "MTR Tai Koo station, then walk uphill" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.285,114.221", source: "https://hongkongclimbing.com/routes/hong-kong/tai-koo-boulders/" },
    { id: 41, typeCode: 'NB', lat: 22.208, lng: 114.256, diff: "V0 - V6", grades: { boulder: { min: "V0", max: "V6" } }, name: { zh: "鶴咀抱石", en: "Hok Tsui Blocs" }, desc: { zh: "鶴咀半島東南端的海邊花崗岩抱石區。", en: "Coastal granite boulders on the Hok Tsui peninsula." }, trans: { zh: "筲箕灣乘9號巴士至鶴咀", en: "Bus 9 from Shau Kei Wan to Hok Tsui" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.208,114.256", source: "https://hongkongclimbing.com/blocs/hok-tsui/" },
    { id: 42, typeCode: 'NB', lat: 22.348, lng: 114.174, diff: "V0 - V8", grades: { boulder: { min: "V0", max: "V8" } }, name: { zh: "筆架山抱石", en: "Beacon Hill Bouldering" }, desc: { zh: "筆架山一帶的天然抱石區，與攀登岩壁毗鄰。", en: "Natural bouldering sectors on Beacon Hill, next to its crags." }, trans: { zh: "石硤尾乘小巴上山", en: "Minibus from Shek Kip Mei uphill" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.348,114.174", source: "https://hongkongclimbing.com/beacon-bouldering/" },
    { id: 43, typeCode: 'NB', lat: 22.344, lng: 114.219, diff: "V0 - V8", grades: { boulder: { min: "V0", max: "V8" } }, name: { zh: "飛鵝山抱石", en: "Kowloon Peak Bouldering" }, desc: { zh: "飛鵝山一帶的天然抱石區，俯瞰九龍與港島。", en: "Natural bouldering on Fei Ngo Shan overlooking Kowloon." }, trans: { zh: "彩虹乘小巴上山", en: "Minibus from Choi Hung uphill" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.344,114.219", source: "https://hongkongclimbing.com/routes/kowloon/kowloon-peak/kowloon-peak-bouldering/" },
    { id: 44, typeCode: 'NB', lat: 22.352, lng: 114.185, diff: "V0 - V8", grades: { boulder: { min: "V0", max: "V8" } }, name: { zh: "獅子山抱石", en: "Lion Rock Boulders" }, desc: { zh: "獅子山一帶的花崗岩抱石區。", en: "Granite bouldering sectors around Lion Rock." }, trans: { zh: "慈雲山徒步上山", en: "Hike up from Tsz Wan Shan" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.352,114.185", source: "https://hongkongclimbing.com/blocs/lion-rock-boulders/" },
    { id: 45, typeCode: 'NB', lat: 22.340, lng: 114.160, diff: "V0 - V8", grades: { boulder: { min: "V0", max: "V8" } }, name: { zh: "日落森林", en: "Sunset Forest" }, desc: { zh: "九龍獅子山一帶的抱石區，岩面朝西可觀日落。", en: "A bouldering area near Lion Rock with west-facing rock and sunset views." }, trans: { zh: "九龍塘乘小巴至獅子山一帶", en: "Minibus from Kowloon Tong toward Lion Rock" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.340,114.160", source: "https://hongkongclimbing.com/routes/kowloon/sunset-forest/" },
    { id: 46, typeCode: 'NB', lat: 22.336, lng: 114.200, diff: "V0 - V6", grades: { boulder: { min: "V0", max: "V6" } }, name: { zh: "鑽石山抱石", en: "Diamond Blocs" }, desc: { zh: "鑽石山一帶的天然抱石區。", en: "Natural bouldering sectors around Diamond Hill." }, trans: { zh: "港鐵鑽石山站步行", en: "MTR Diamond Hill station, then walk" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.336,114.200", source: "https://hongkongclimbing.com/blocs/diamond-blocs/" },
    { id: 47, typeCode: 'NB', lat: 22.345, lng: 114.140, diff: "V0 - V7", grades: { boulder: { min: "V0", max: "V7" } }, name: { zh: "象山抱石", en: "Middle Hill" }, desc: { zh: "筆架山側象山一帶的花崗岩抱石區。", en: "Granite bouldering around Middle Hill beside Beacon Hill." }, trans: { zh: "石硤尾徒步上山", en: "Hike up from Shek Kip Mei" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.345,114.140", source: "https://hongkongclimbing.com/blocs/middle-hill/" },
    { id: 48, typeCode: 'NB', lat: 22.430, lng: 114.110, diff: "V0 - V8", grades: { boulder: { min: "V0", max: "V8" } }, name: { zh: "雞公嶺抱石", en: "Kai Kung Leng" }, desc: { zh: "新界雞公嶺一帶的天然抱石區。", en: "Natural bouldering around Kai Kung Leng in the New Territories." }, trans: { zh: "元朗或錦田乘車至雞公嶺一帶", en: "Travel from Yuen Long or Kam Tin toward Kai Kung Leng" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.430,114.110", source: "https://hongkongclimbing.com/routes/new-territories/kai-kung-leng/" },
    { id: 49, typeCode: 'NB', lat: 22.390, lng: 114.240, diff: "V0 - V7", grades: { boulder: { min: "V0", max: "V7" } }, name: { zh: "水牛山抱石", en: "Buffalo Boulders" }, desc: { zh: "馬鞍山一帶水牛山的天然抱石區。", en: "Natural bouldering on Buffalo Hill near Ma On Shan." }, trans: { zh: "馬鞍山徒步上山", en: "Hike up from Ma On Shan" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.390,114.240", source: "https://hongkongclimbing.com/blocs/buffalo-boulders/" },
    { id: 50, typeCode: 'NB', lat: 22.480, lng: 114.180, diff: "V0 - V7", grades: { boulder: { min: "V0", max: "V7" } }, name: { zh: "馬騮溪抱石", en: "Ma Tai Boulders" }, desc: { zh: "八仙嶺馬騮溪一帶的天然抱石區。", en: "Natural bouldering along Ma Tai Stream in Pat Sin Leng." }, trans: { zh: "大埔乘巴士至八仙嶺一帶", en: "Bus from Tai Po toward Pat Sin Leng" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.480,114.180", source: "https://hongkongclimbing.com/routes/new-territories/ma-tai-stream/ma-tai-boulders/" },
    { id: 51, typeCode: 'NB', lat: 22.233, lng: 113.960, diff: "V0 - V6", grades: { boulder: { min: "V0", max: "V6" } }, name: { zh: "長沙海灘抱石", en: "Cheung Sha Beach Boulders" }, desc: { zh: "大嶼山長沙海灘一帶的花崗岩抱石區。", en: "Granite bouldering near Cheung Sha Beach on Lantau." }, trans: { zh: "東涌乘巴士至長沙", en: "Bus from Tung Chung to Cheung Sha" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.233,113.960", source: "https://hongkongclimbing.com/routes/lantau/cheung-sha-beach-boulders/" },
    { id: 52, typeCode: 'NB', lat: 22.331, lng: 114.265, diff: "N/A", grades: null, name: { zh: "白水碗", en: "Pak Shui Wun" }, desc: { zh: "清水灣大埔仔一帶的海邊抱石區。", en: "Seaside bouldering near Tai Po Tsai on Clear Water Bay." }, trans: { zh: "坑口乘小巴至科大一帶", en: "Minibus from Hang Hau toward HKUST" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.331,114.265", source: "https://hongkongclimbing.com/pak-shui-wun/" },
    { id: 53, typeCode: 'NB', lat: 22.400, lng: 114.250, diff: "N/A", grades: null, name: { zh: "鱷魚抱石（鹿巢山）", en: "Crocodile Blocs (Luk Chau Shan)" }, desc: { zh: "馬鞍山鹿巢山一帶的天然抱石區。", en: "Natural bouldering around Luk Chau Shan near Ma On Shan." }, trans: { zh: "馬鞍山徒步上山", en: "Hike up from Ma On Shan" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.400,114.250", source: "https://hongkongclimbing.com/blocs/luk-chau-shan/" },

    // --- Outdoor climbing (NC) - catalog completion ---
    { id: 54, typeCode: 'NC', lat: 22.267, lng: 114.206, diff: "F5A - F7A", grades: { rope: { min: "F5A", max: "F7A" } }, name: { zh: "寶馬山", en: "Mount Butler" }, desc: { zh: "港島東寶馬山一帶的岩壁攀登區。", en: "Crags around Mount Butler on eastern Hong Kong Island." }, trans: { zh: "港鐵太古站乘車上山", en: "Travel uphill from Tai Koo MTR station" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.267,114.206", source: "https://hongkongclimbing.com/mount-butler/" },
    { id: 55, typeCode: 'NC', lat: 22.463, lng: 114.335, diff: "F5A - F7A", grades: { rope: { min: "F5A", max: "F7A" } }, name: { zh: "海下", en: "Hoi Ha" }, desc: { zh: "西貢海下一帶的海崖攀登區。", en: "Sea cliff climbing around Hoi Ha in Sai Kung." }, trans: { zh: "西貢乘小巴至海下", en: "Minibus from Sai Kung to Hoi Ha" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.463,114.335", source: "https://hongkongclimbing.com/routes/hoi-ha/" },
    { id: 56, typeCode: 'NC', lat: 22.389, lng: 113.960, diff: "F4 - F7B", grades: { rope: { min: "F4", max: "F7B" } }, name: { zh: "屯門岩場", en: "Tuen Mun Crags" }, desc: { zh: "屯門青山一帶的岩壁攀登區。", en: "Crags around Castle Peak in Tuen Mun." }, trans: { zh: "屯門徒步上山", en: "Hike up from Tuen Mun" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.389,113.960", source: "https://hongkongclimbing.com/routes/tuen-mun-crags/" },
    { id: 57, typeCode: 'NC', lat: 22.410, lng: 114.240, diff: "F4 - F7A", grades: { rope: { min: "F4", max: "F7A" } }, name: { zh: "馬鞍山谷", en: "Ma On Shan Valley" }, desc: { zh: "馬鞍山一帶山谷的岩壁攀登區。", en: "Valley crags around Ma On Shan." }, trans: { zh: "馬鞍山乘巴士或徒步", en: "Bus or hike from Ma On Shan" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.410,114.240", source: "https://hongkongclimbing.com/ma-on-shan-valley/" },
    { id: 58, typeCode: 'NC', lat: 22.205, lng: 114.130, diff: "F4 - F7B", grades: { rope: { min: "F4", max: "F7B" } }, name: { zh: "南丫島索罟灣", en: "Lamma Sok Kwu" }, desc: { zh: "南丫島索罟灣及山地塘一帶的攀登區。", en: "Climbing around Sok Kwu Wan and Mount Stenhouse on Lamma." }, trans: { zh: "中環或香港仔乘渡輪至索罟灣", en: "Ferry from Central or Aberdeen to Sok Kwu Wan" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.205,114.130", source: "https://hongkongclimbing.com/sok-kwu-wall/" },
    { id: 59, typeCode: 'NC', lat: 22.225, lng: 113.900, diff: "F4 - F7B", grades: { rope: { min: "F4", max: "F7B" } }, name: { zh: "大嶼山鷹岩", en: "Lantau Eagle Crag" }, desc: { zh: "大嶼山鷹岩及白芒一帶的攀登區。", en: "Climbing around Eagle Crag and Pak Mong on Lantau." }, trans: { zh: "東涌乘巴士或徒步", en: "Bus or hike from Tung Chung" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.225,113.900", source: "https://hongkongclimbing.com/routes/lantau/eagle-crag/" },
    { id: 60, typeCode: 'NC', lat: 22.225, lng: 114.235, diff: "F5A - F7A", grades: { rope: { min: "F5A", max: "F7A" } }, name: { zh: "土地灣", en: "To Tei Wan Crag" }, desc: { zh: "港島東南土地灣一帶的岩壁攀登區。", en: "Crags around To Tei Wan on southeastern Hong Kong Island." }, trans: { zh: "筲箕灣乘巴士至土地灣", en: "Bus from Shau Kei Wan to To Tei Wan" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.225,114.235", source: "https://www.thecrag.com/en/climbing/hong-kong/hong-kong-island/area/4434864570" },
    { id: 61, typeCode: 'NC', lat: 22.290, lng: 114.300, diff: "F5A - F7A", grades: { rope: { min: "F5A", max: "F7A" } }, name: { zh: "大坑墩", en: "Tai Hang Tun" }, desc: { zh: "清水灣半島大坑墩一帶的攀登區。", en: "Climbing around Tai Hang Tun on Clear Water Bay Peninsula." }, trans: { zh: "坑口乘巴士至清水灣", en: "Bus from Hang Hau to Clear Water Bay" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.290,114.300", source: "https://hongkongclimbing.com/routes/new-territories/tai-hang-tun/" },
    { id: 62, typeCode: 'NC', lat: 22.250, lng: 113.900, diff: "F5A - F7A", grades: { rope: { min: "F5A", max: "F7A" } }, name: { zh: "昂田", en: "Ngong Tin" }, desc: { zh: "大嶼山昂田一帶的攀登區。", en: "Climbing around Ngong Tin on Lantau." }, trans: { zh: "大嶼山乘車至昂田一帶", en: "Travel toward Ngong Tin on Lantau" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.250,113.900", source: "https://www.thecrag.com/en/climbing/hong-kong/new-territories/area/12870132894" },

    // --- Gym bouldering (AB) - catalog completion ---
    { id: 63, typeCode: 'AB', lat: 22.391, lng: 114.207, diff: "N/A", grades: null, name: { zh: "JUST CLIMB (石門)", en: "JUST CLIMB (Shek Mun)" }, desc: { zh: "石門新貿中心內的室內抱石館。", en: "Indoor bouldering gym at New Commerce Centre in Shek Mun." }, trans: { zh: "港鐵石門站", en: "MTR Shek Mun station" }, address: { zh: "沙田石門安平街6號新貿中心地下4室", en: "Room 4, G/F, Block A, New Trade Plaza, 6 On Ping Street, Shek Mun, Sha Tin, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.391,114.207", source: "https://justclimb.hk/visit-us/" },
    { id: 64, typeCode: 'AB', lat: 22.367, lng: 114.116, diff: "N/A", grades: null, name: { zh: "JUST CLIMB (荃灣)", en: "JUST CLIMB (Tsuen Wan)" }, desc: { zh: "荃灣 Plaza 88 商場內的室內抱石館。", en: "Indoor bouldering gym at Plaza 88 in Tsuen Wan." }, trans: { zh: "港鐵荃灣西站", en: "MTR Tsuen Wan West station" }, address: { zh: "香港新界荃灣楊屋道88號Plaza 88 8樓802號舖", en: "Shop 802, 8/F, Plaza 88, 88 Yeung Uk Road, Tsuen Wan, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.367,114.116", source: "https://justclimb.hk/visit-us/" },
    { id: 65, typeCode: 'AB', lat: 22.285, lng: 114.212, diff: "N/A", grades: null, name: { zh: "JUST CLIMB (太古)", en: "JUST CLIMB (Tai Koo)" }, desc: { zh: "鰂魚涌英皇道的室內抱石館。", en: "Indoor bouldering gym on King's Road, Quarry Bay." }, trans: { zh: "港鐵太古站", en: "MTR Tai Koo station" }, address: { zh: "香港鰂魚涌英皇道1001號6樓01室", en: "Shop 1, 6/F, 1001 King's Road, Quarry Bay, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.285,114.212", source: "https://justclimb.hk/visit-us/" },
    { id: 66, typeCode: 'AB', lat: 22.426, lng: 114.267, diff: "N/A", grades: null, name: { zh: "JUST CLIMB (西沙)", en: "JUST CLIMB (Sai Sha)" }, desc: { zh: "西沙 GO PARK 內的室內抱石館。", en: "Indoor bouldering gym at Sai Sha GO PARK." }, trans: { zh: "馬鞍山乘巴士至西沙", en: "Bus from Ma On Shan to Sai Sha" }, address: { zh: "西沙海映路9號西沙GO PARK", en: "Sai Sha GO PARK, 9 Hoi Ying Road, Sai Sha, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.426,114.267", source: "https://justclimb.hk/visit-us/" },
    { id: 67, typeCode: 'AB', lat: 22.374, lng: 114.109, diff: "N/A", grades: null, name: { zh: "Vita Beta (荃灣)", en: "Vita Beta (Tsuen Wan)" }, desc: { zh: "荃灣沙咀道科技中心內的室內抱石館。", en: "Indoor bouldering gym at Technology Plaza on Sha Tsui Road, Tsuen Wan." }, trans: { zh: "港鐵荃灣站步行", en: "MTR Tsuen Wan station, then walk" }, address: { zh: "香港荃灣沙咀道29-35號科技中心1樓2號室", en: "Unit 2, 1/F, Technology Plaza, 29-35 Sha Tsui Road, Tsuen Wan, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.374,114.109", source: "https://gowherehou.com/listing/vita-beta-climbing-gym/" },

    // --- Gym climbing (AC) - catalog completion ---
    { id: 68, typeCode: 'AC', lat: 22.292, lng: 114.239, diff: "Top Rope/Lead", grades: null, name: { zh: "鯉魚門體育館", en: "Lei Yue Mun Sports Centre" }, desc: { zh: "康文署油塘鯉魚門體育館內的室內攀石牆，高11米，設9條攀登線。", en: "LCSD indoor climbing wall at Lei Yue Mun Sports Centre, 11m tall with 9 routes." }, trans: { zh: "港鐵油塘站A2出口", en: "MTR Yau Tong station Exit A2" }, address: { zh: "九龍油塘鯉魚門市政大廈2樓至5樓", en: "2/F to 5/F, Lei Yue Mun Municipal Services Building, Yau Tong, Kowloon" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.292,114.239", source: "https://www.lcsd.gov.hk/clpss/tc/webApp/Facility/Details.do?fid=980" },
    { id: 69, typeCode: 'AC', lat: 22.338, lng: 114.199, diff: "Top Rope/Lead", grades: null, name: { zh: "東啟德體育館", en: "Kai Tak East Sports Centre" }, desc: { zh: "康文署新蒲崗東啟德體育館內的室內攀石牆，高7米，設20條攀登線。", en: "LCSD indoor climbing wall at Kai Tak East Sports Centre, 7m tall with 20 routes." }, trans: { zh: "港鐵鑽石山站B出口步行約10分鐘", en: "MTR Diamond Hill station Exit B, about 10 min walk" }, address: { zh: "九龍新蒲崗六合街30號", en: "30 Luk Hop Street, San Po Kong, Kowloon" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.338,114.199", source: "https://www.lcsd.gov.hk/clpss/tc/webApp/Facility/Details.do?fid=726" },
    { id: 70, typeCode: 'AC', lat: 22.306, lng: 114.255, diff: "Top Rope/Lead", grades: null, name: { zh: "調景嶺體育館", en: "Tiu Keng Leng Sports Centre" }, desc: { zh: "康文署調景嶺體育館設有戶外攀石牆。", en: "LCSD Tiu Keng Leng Sports Centre features an outdoor climbing wall." }, trans: { zh: "港鐵調景嶺站", en: "MTR Tiu Keng Leng station" }, address: { zh: "將軍澳翠嶺路2號", en: "2 Chui Ling Road, Tseung Kwan O, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.306,114.255", source: "https://www.lcsd.gov.hk/clpss/tc/webApp/Facility/Details.do?ftid=0&did=18" },
    { id: 71, typeCode: 'AB', lat: 22.302, lng: 114.257, diff: "N/A", grades: null, name: { zh: "JUST CLIMB (將軍澳)", en: "JUST CLIMB (Tseung Kwan O)" }, desc: { zh: "將軍澳海天晉滙(Ocean PopWalk)商場內的室內抱石館。", en: "Indoor bouldering gym at Ocean PopWalk in Tseung Kwan O." }, trans: { zh: "將軍澳站A1出口步行約10分鐘", en: "About 10 min walk from Tseung Kwan O station Exit A1" }, address: { zh: "香港新界將軍澳唐賢街33號Capri商場B03舖", en: "Shop B03, Basement, Capri Place, 33 Tong Yin Street, Tseung Kwan O, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.302,114.257", source: "https://justclimb.hk/" },
    // --- Exhaustive enumeration additions (2026-09, re-landed) ---
    { id: 72, typeCode: 'AB', lat: 22.451, lng: 114.029, diff: "N/A", grades: null, name: { zh: "香港攀爬樂園 (元朗)", en: "HK Climbing Park (Yuen Long)" }, desc: { zh: "香港攀爬樂園的元朗分店，設室內抱石區。", en: "Yuen Long branch of HK Climbing Park with indoor bouldering." }, trans: { zh: "港鐵朗屏站步行至朗壹廣場", en: "MTR Long Ping station, walk to One North" }, address: { zh: "香港新界元朗宏業西街朗壹廣場（One North）", en: "One North, Wang Yip Street West, Tung Tau Industrial Area, Yuen Long, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.451,114.029", source: "https://www.hkclimbingpark.com/" },
    { id: 73, typeCode: 'AB', lat: 22.397, lng: 113.969, diff: "N/A", grades: null, name: { zh: "JUST CLIMB (屯門)", en: "JUST CLIMB (Tuen Mun)" }, desc: { zh: "屯門的室內抱石館。", en: "Indoor bouldering gym in Tuen Mun." }, trans: { zh: "港鐵屯門站", en: "MTR Tuen Mun station" }, address: { zh: "香港新界屯門建發里4號地下1號舖", en: "Shop 1, G/F, The Ulferts Warehouse Centre, 4 Kin Fat Lane, Tuen Mun, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.397,113.969", source: "https://justclimb.hk/visit-us/" },
    { id: 74, typeCode: 'NC', lat: 22.381, lng: 114.006, diff: "N/A", grades: null, name: { zh: "沙龍岩場", en: "Salong Crag" }, desc: { zh: "屯門一帶的岩壁攀登區。", en: "Crag near Tuen Mun." }, trans: { zh: "屯門徒步上山", en: "Hike up from Tuen Mun" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.381,114.006", source: "https://hongkongclimbing.com/routes/new-territories/salong-crag/" },
    { id: 75, typeCode: 'NC', lat: 22.291, lng: 114.020, diff: "N/A", grades: null, name: { zh: "黑鳶崖", en: "Black Kite Crag" }, desc: { zh: "大嶼山愉景灣一帶的運動攀登岩場。", en: "Sport climbing crag on Lantau near Discovery Bay." }, trans: { zh: "東涌乘巴士至愉景灣一帶", en: "Bus from Tung Chung toward Discovery Bay" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.291,114.020", source: "https://www.thecrag.com/en/climbing/hong-kong/lantau-island/area/12484987" },
    { id: 76, typeCode: 'NC', lat: 22.230, lng: 113.984, diff: "N/A", grades: null, name: { zh: "寺岩", en: "Temple Crag" }, desc: { zh: "大嶼山白芒一帶的攀登岩場。", en: "Climbing crag near Pak Mong on Lantau." }, trans: { zh: "東涌乘巴士至白芒", en: "Bus from Tung Chung to Pak Mong" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.230,113.984", source: "https://www.mountainproject.com/area/110814095/temple-crag" },
    { id: 77, typeCode: 'NC', lat: 22.356, lng: 114.374, diff: "N/A", grades: null, name: { zh: "白崖頭（瀑布岩）", en: "Pak Ngai Tau (Waterfall Rock)" }, desc: { zh: "西貢東海岸的傳統攀登海崖。", en: "Sea cliff trad climbing on the east coast of Sai Kung." }, trans: { zh: "西貢乘車至萬宜水庫東壩一帶", en: "Travel from Sai Kung toward High Island Reservoir East Dam" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.356,114.374", source: "https://www.thecrag.com/climbing/hong-kong/waterfall-rock" },
    { id: 78, typeCode: 'NC', lat: 22.258, lng: 114.186, diff: "N/A", grades: null, name: { zh: "聶高信山", en: "Mount Nicholson (Black's Link)" }, desc: { zh: "港島聶高信山一帶的岩壁，含傳統與運動攀登線。", en: "Crags on Mount Nicholson with trad and sport routes." }, trans: { zh: "黃泥涌峽徒步上山", en: "Hike up from Wong Nai Chung Gap" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.258,114.186", source: "https://www.ukclimbing.com/logbook/crags/mount_nicholson-21396/" },
    { id: 79, typeCode: 'NC', lat: 22.283, lng: 114.197, diff: "N/A", grades: null, name: { zh: "猴崖（寶馬山）", en: "Monkey Buttress (Braemar Hill)" }, desc: { zh: "港島寶馬山一帶的岩壁，含傳統與運動攀登線。", en: "Crag on Braemar Hill with trad and sport routes." }, trans: { zh: "北角徒步上山", en: "Hike up from North Point" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.283,114.197", source: "https://27crags.com/crags/monkey-buttress-braemar-hill/description" },
    { id: 80, typeCode: 'NC', lat: 22.240, lng: 114.292, diff: "N/A", grades: null, name: { zh: "佛堂角", en: "Tathong Point" }, desc: { zh: "清水灣半島南端的運動攀登海崖。", en: "Sport climbing sea cliffs at the southern tip of Clear Water Bay Peninsula." }, trans: { zh: "清水灣乘小巴至布袋澳一帶", en: "Minibus from Clear Water Bay toward Po Toi O" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.240,114.292", source: "https://hongkongclimbing.com/routes/tung-lung-chau-2/tathong-point/" },
    { id: 81, typeCode: 'NC', lat: 22.316, lng: 114.358, diff: "N/A", grades: null, name: { zh: "破邊洲", en: "Po Pin Chau" }, desc: { zh: "西貢東海岸的海崖攀登區。", en: "Sea cliff climbing off the east coast of Sai Kung." }, trans: { zh: "西貢乘車至萬宜水庫東壩再乘船", en: "Travel from Sai Kung to High Island East Dam, then boat" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.316,114.358", source: "https://hongkongclimbing.com/routes/new-territories/po-ping-chau/" },
    { id: 82, typeCode: 'NC', lat: 22.262, lng: 114.137, diff: "N/A", grades: null, name: { zh: "薄扶林", en: "Pok Fu Lam" }, desc: { zh: "港島薄扶林一帶的岩壁攀登區。", en: "Crags around Pok Fu Lam on Hong Kong Island." }, trans: { zh: "港鐵香港大學站步行上山", en: "MTR HKU station, then walk uphill" }, address: null, gmap: "https://www.google.com/maps/search/?api=1&query=22.262,114.137", source: "https://hongkongclimbing.com/routes/hong-kong/pok-fu-lam/" },
    { id: 83, typeCode: 'AC', lat: 22.285, lng: 114.222, diff: "Top Rope/Lead", grades: null, name: { zh: "港島東體育館", en: "Island East Sports Centre" }, desc: { zh: "康文署轄下體育館設有公共攀石牆。", en: "LCSD sports centre featuring a public climbing wall." }, trans: { zh: "港鐵西灣河站", en: "MTR Sai Wan Ho station" }, address: { zh: "香港西灣河鯉景道52號", en: "52 Lei King Road, Sai Wan Ho, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.285,114.222", source: "https://www.lcsd.gov.hk/clpss/tc/webApp/Facility/Details.do?fid=1451" },
    { id: 84, typeCode: 'AC', lat: 22.366, lng: 114.113, diff: "Top Rope/Lead", grades: null, name: { zh: "荃灣體育館", en: "Tsuen Wan Sports Centre" }, desc: { zh: "康文署轄下體育館設有公共攀石牆。", en: "LCSD sports centre featuring a public climbing wall." }, trans: { zh: "港鐵荃灣西站", en: "MTR Tsuen Wan West station" }, address: { zh: "香港新界荃灣永順街53號", en: "53 Wing Shun Street, Tsuen Wan, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.366,114.113", source: "https://www.lcsd.gov.hk/clpss/tc/webApp/Facility/Details.do?fid=2119" },
    { id: 85, typeCode: 'AC', lat: 22.351, lng: 114.102, diff: "Top Rope/Lead", grades: null, name: { zh: "青衣西南體育館", en: "Tsing Yi Southwest Sports Centre" }, desc: { zh: "康文署轄下體育館設有公共攀石牆。", en: "LCSD sports centre featuring a public climbing wall." }, trans: { zh: "港鐵青衣站", en: "MTR Tsing Yi station" }, address: { zh: "香港新界青衣涌美路70號青衣西南康體大樓", en: "Tsing Yi Southwest Leisure Building, 70 Chung Mei Road, Tsing Yi, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.351,114.102", source: "https://www.lcsd.gov.hk/clpss/tc/webApp/Facility/Details.do?fid=1450" },
    { id: 86, typeCode: 'AC', lat: 22.380, lng: 114.205, diff: "Top Rope/Lead", grades: null, name: { zh: "圓洲角體育館", en: "Yuen Chau Kok Sports Centre" }, desc: { zh: "康文署轄下體育館設有公共攀石牆。", en: "LCSD sports centre featuring a public climbing wall." }, trans: { zh: "港鐵第一城站", en: "MTR City One station" }, address: { zh: "香港新界沙田銀城街35號圓洲角綜合大樓", en: "Yuen Chau Kok Complex, 35 Ngan Shing Street, Sha Tin, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.380,114.205", source: "https://www.lcsd.gov.hk/clpss/tc/webApp/Facility/Details.do?fid=1311" },
    { id: 87, typeCode: 'AC', lat: 22.337, lng: 114.170, diff: "Top Rope/Lead", grades: null, name: { zh: "石硤尾公園體育館", en: "Shek Kip Mei Park Sports Centre" }, desc: { zh: "康文署轄下體育館設有公共攀石牆。", en: "LCSD sports centre featuring a public climbing wall." }, trans: { zh: "港鐵石硤尾站", en: "MTR Shek Kip Mei station" }, address: { zh: "香港九龍深水埗南昌街290號", en: "290 Nam Cheong Street, Sham Shui Po, Kowloon, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.337,114.170", source: "https://www.lcsd.gov.hk/clpss/tc/webApp/Facility/Details.do?fid=692" },
    { id: 88, typeCode: 'AC', lat: 22.330, lng: 114.225, diff: "Top Rope/Lead", grades: null, name: { zh: "順利邨體育館", en: "Shun Lee Tsuen Sports Centre" }, desc: { zh: "康文署轄下體育館設有公共攀石牆。", en: "LCSD sports centre featuring a public climbing wall." }, trans: { zh: "港鐵觀塘站轉小巴", en: "MTR Kwun Tong station, then minibus" }, address: { zh: "九龍觀塘順利邨道33號", en: "33 Shun Lee Tsuen Road, Kwun Tong, Kowloon, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.330,114.225", source: "https://www.lcsd.gov.hk/clpss/tc/webApp/Facility/Details.do?fid=1007" },
    { id: 89, typeCode: 'AC', lat: 22.497, lng: 114.128, diff: "Top Rope/Lead", grades: null, name: { zh: "保榮路體育館", en: "Po Wing Road Sports Centre" }, desc: { zh: "康文署轄下體育館設有公共攀石牆。", en: "LCSD sports centre featuring a public climbing wall." }, trans: { zh: "港鐵上水站", en: "MTR Sheung Shui station" }, address: { zh: "新界上水百和路19號", en: "19 Pak Wo Road, Sheung Shui, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.497,114.128", source: "https://www.lcsd.gov.hk/clpss/tc/webApp/Facility/Details.do?fid=1148" },
    { id: 90, typeCode: 'AC', lat: 22.465, lng: 113.997, diff: "Top Rope/Lead", grades: null, name: { zh: "天暉路體育館", en: "Tin Fai Road Sports Centre" }, desc: { zh: "康文署轄下體育館設有公共攀石牆。", en: "LCSD sports centre featuring a public climbing wall." }, trans: { zh: "港鐵天水圍站", en: "MTR Tin Shui Wai station" }, address: { zh: "新界天水圍天瑞路63號", en: "63 Tin Shui Road, Tin Shui Wai, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.465,113.997", source: "https://www.lcsd.gov.hk/clpss/tc/webApp/Facility/Details.do?fid=1273" },
    { id: 91, typeCode: 'AC', lat: 22.384, lng: 113.980, diff: "Top Rope/Lead", grades: null, name: { zh: "兆麟體育館", en: "Siu Lun Sports Centre" }, desc: { zh: "康文署轄下體育館設有公共攀石牆。", en: "LCSD sports centre featuring a public climbing wall." }, trans: { zh: "輕鐵兆麟站", en: "LRT Siu Lun stop" }, address: { zh: "新界屯門兆麟街19號", en: "19 Siu Lun Street, Tuen Mun, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.384,113.980", source: "https://www.lcsd.gov.hk/clpss/tc/webApp/Facility/Details.do?fid=2192" },
    // --- 18-district scan additions (2026-09) ---
    { id: 92, typeCode: 'AB', lat: 22.303, lng: 114.261, diff: "N/A", grades: null, name: { zh: "Kizuna 攀石館 (將軍澳)", en: "Kizuna Climbing Gym (Tseung Kwan O)" }, desc: { zh: "將軍澳海天晉滙的室內抱石館。", en: "Indoor bouldering gym at Ocean PopWalk in Tseung Kwan O." }, trans: { zh: "港鐵將軍澳站步行至海天晉滙", en: "MTR Tseung Kwan O station, walk to Ocean PopWalk" }, address: { zh: "將軍澳唐俊街28號海天晉匯1樓120C-D舖", en: "Shop 120C-D, 1/F, Ocean PopWalk, 28 Tong Chun Street, Tseung Kwan O, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.303,114.261", source: "https://www.freeguider.com/en/blogs/346/909" },
    { id: 93, typeCode: 'AB', lat: 22.313, lng: 114.220, diff: "N/A", grades: null, name: { zh: "BoulderMAD 攀石場 (觀塘)", en: "BoulderMAD Climbing Gym (Kwun Tong)" }, desc: { zh: "觀塘的室內抱石館。", en: "Indoor bouldering gym in Kwun Tong." }, trans: { zh: "港鐵觀塘站", en: "MTR Kwun Tong station" }, address: { zh: "觀塘鴻圖道26號威登中心302-303室", en: "Room 302-303, Westin Centre, 26 Hung To Road, Kwun Tong, Kowloon, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.313,114.220", source: "https://panpa.hk/listing/bouldermad-climbing-gym/" },
    { id: 94, typeCode: 'AB', lat: 22.278, lng: 114.174, diff: "N/A", grades: null, name: { zh: "N Bouldering (灣仔)", en: "N Bouldering (Wan Chai)" }, desc: { zh: "灣仔軒尼詩道商廈內的室內抱石館。", en: "Indoor bouldering gym in a commercial building on Hennessy Road, Wan Chai." }, trans: { zh: "港鐵灣仔站", en: "MTR Wan Chai station" }, address: { zh: "灣仔軒尼詩道245-251號守時商業大廈24樓", en: "24/F, Success Commercial Building, 245-251 Hennessy Road, Wan Chai, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.278,114.174", source: "https://www.corner.inc/place/pQQXzoCSsrXm" },
    { id: 95, typeCode: 'AB', lat: 22.397, lng: 113.966, diff: "N/A", grades: null, name: { zh: "Top Out Climbing (屯門)", en: "Top Out Climbing (Tuen Mun)" }, desc: { zh: "屯門山景商場內的室內攀石場。", en: "Indoor climbing gym at Shan King Shopping Centre in Tuen Mun." }, trans: { zh: "港鐵屯門站轉乘輕鐵至山景", en: "MTR Tuen Mun station, then LRT to Shan King" }, address: { zh: "屯門鳴琴路1號山景商場低層地下126號舖", en: "Shop 126, Lower Ground Floor, Shan King Shopping Centre, Shan King Estate, 1 Ming Kum Road, Tuen Mun, New Territories, Hong Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.397,113.966", source: "https://news.hket.com/article/3495327" },
  ];

  // Generate the display string from structured grades (null when no grades).
  function formatGrade(grades) {
    if (!grades) return null;
    if (grades.boulder) return grades.boulder.min + ' - ' + grades.boulder.max;
    if (grades.rope) return grades.rope.min + ' - ' + grades.rope.max;
    return null;
  }

  // Display string for a spot: generated from grades, or the raw diff fallback.
  function gradeText(spot) {
    var formatted = formatGrade(spot && spot.grades);
    return formatted !== null && formatted !== undefined ? formatted : ((spot && spot.diff) || '');
  }

  return { spots: spots, formatGrade: formatGrade, gradeText: gradeText };
});