/**
 * js/spots-data.js - single source of truth for all climbing spots.
 *
 * UMD: a browser classic <script> exposes window.SPOTS_DATA; Node import gets
 * the same object via module.exports (default import).
 *
 * Each spot keeps `diff` (the original raw difficulty display string, verbatim
 * from the old inline data) plus a structured `grades` object used for
 * filtering/validation. Spots without a structured difficulty (e.g.
 * "Top Rope/Lead") have grades: null and `diff` remains their display text.
 */
(function (root, factory) {
  if (typeof module === 'object' && module && module.exports) {
    module.exports = factory();
  } else {
    root.SPOTS_DATA = factory();
  }
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  var spots = [
    // --- Outdoor bouldering (NB) ---
    { id: 1, typeCode: 'NB', lat: 22.213, lng: 114.200, diff: "VB - V12", grades: { boulder: { min: "VB", max: "V12" } }, name: { zh: "舂坎角", en: "Chung Hom Kok" }, desc: { zh: "約97條路線，花崗岩。路況包括手足並用的攀爬石壁。", en: "Around 97 routes on granite. Includes scrambling sections." }, trans: { zh: "中環乘6X等巴士至舂坎角道", en: "Bus 6X from Central to Chung Hom Kok Rd" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.213,114.200", source: "https://hongkongclimbing.com/routes/hong-kong/chung-hom-kok-boulders/" },
    { id: 2, typeCode: 'NB', lat: 22.228, lng: 114.251, diff: "VB - V12+", grades: { boulder: { min: "VB", max: "V12+" } }, name: { zh: "石澳 - 抱石區", en: "Shek O - Bouldering" }, desc: { zh: "約143條路線。大頭洲「九宮格」是馳名攀石地。", en: "143 routes. Tai Tau Chau is famous for its intricate rock textures." }, trans: { zh: "筲箕灣乘9號巴士", en: "Bus 9 from Shau Kei Wan" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.228,114.251", source: "https://www.thecrag.com/en/climbing/hong-kong/hong-kong-island/area/12484819" },
    { id: 3, typeCode: 'NB', lat: 22.245, lng: 114.290, diff: "VB - V12", grades: { boulder: { min: "VB", max: "V12" } }, name: { zh: "東龍洲 - 抱石", en: "Tung Lung Chau - Boulder" }, desc: { zh: "東海岸佈滿懸崖峭壁，表面粗糙，摩擦力極佳。", en: "East coast cliffs with excellent rough friction." }, trans: { zh: "西灣河/三家村乘街渡", en: "Ferry from Sai Wan Ho / Sam Ka Tsuen" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.245,114.290", source: "https://hongkongclimbing.com/blocs/tung-lung-bouldering/" },
    { id: 4, typeCode: 'NB', lat: 22.200, lng: 114.130, diff: "VB - V10", grades: { boulder: { min: "VB", max: "V10" } }, name: { zh: "南丫島", en: "Lamma Island" }, desc: { zh: "山地塘一帶有多處天然抱石，如月老石等。", en: "Multiple natural boulders around Mount Stenhouse." }, trans: { zh: "中環4號碼頭乘渡輪", en: "Ferry from Central Pier 4" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.200,114.130", source: "https://hongkongclimbing.com/routes/lamma/lamma-boulders/" },

    // --- Gym bouldering (AB) ---
    { id: 5, typeCode: 'AB', lat: 22.335, lng: 114.198, diff: "V0 - V10", grades: { boulder: { min: "V0", max: "V10" } }, name: { zh: "JUST CLIMB (新蒲崗店)", en: "JUST CLIMB (San Po Kong)" }, desc: { zh: "超過100條路線，分4大程度12級難度。", en: "Over 100 routes divided into 12 difficulty levels." }, trans: { zh: "新蒲崗", en: "San Po Kong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.335,114.198", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 6, typeCode: 'AB', lat: 22.292, lng: 114.207, diff: "V0 - V7", grades: { boulder: { min: "V0", max: "V7" } }, name: { zh: "Verm City (鰂魚涌)", en: "Verm City (Quarry Bay)" }, desc: { zh: "香港最大抱石場地逾1.8萬呎，設4.5米高牆。", en: "HK's largest gym (18k sq.ft) with 4.5m walls." }, trans: { zh: "鰂魚涌渣華道", en: "Java Road, Quarry Bay" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.292,114.207", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 7, typeCode: 'AB', lat: 22.385, lng: 114.195, diff: "V0 - V7+", grades: { boulder: { min: "V0", max: "V7+" } }, name: { zh: "HK Climbing Park (沙田)", en: "HK Climbing Park (Shatin)" }, desc: { zh: "高達4.5米的室內抱石區域，多達50條抱石路線。", en: "4.5m tall walls with up to 50 bouldering routes." }, trans: { zh: "沙田富豪花園", en: "Belair Gardens, Shatin" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.385,114.195", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 8, typeCode: 'AB', lat: 22.328, lng: 114.163, diff: "V0 - V7", grades: { boulder: { min: "V0", max: "V7" } }, name: { zh: "尚山岩館 (深水埗)", en: "Crux (Sham Shui Po)" }, desc: { zh: "以動物主題分級，設有人氣訓練板Moonboard。", en: "Animal-themed grading, features a Moonboard." }, trans: { zh: "深水埗大南街", en: "Tai Nan Street, Sham Shui Po" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.328,114.163", source: "https://hongkongclimbing.com/climbing-walls/" },

    // --- Outdoor climbing (NC) ---
    { id: 9, typeCode: 'NC', lat: 22.230, lng: 114.250, diff: "F4 - F8A+", grades: { rope: { min: "F4", max: "F8A+" } }, name: { zh: "石澳 - 運動攀登", en: "Shek O - Sport Climbing" }, desc: { zh: "包含日落隙及技術牆，考驗力量與平衡。", en: "Includes Sunset Crack and Tech Wall, testing power & balance." }, trans: { zh: "筲箕灣乘9號巴士", en: "Bus 9 from Shau Kei Wan" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.230,114.250", source: "https://hongkongclimbing.com/routes/hong-kong/shek-o/" },
    { id: 10, typeCode: 'NC', lat: 22.247, lng: 114.288, diff: "F4 - F8A+", grades: { rope: { min: "F4", max: "F8A+" } }, name: { zh: "東龍洲 - 攀登", en: "Tung Lung Chau - Climbing" }, desc: { zh: "崖下海浪咆哮，極具挑戰性的海溝及巨牆。", en: "Challenging sea cliff walls and gullies above crashing waves." }, trans: { zh: "乘街渡前往", en: "Ferry from Sai Wan Ho" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.247,114.288", source: "https://www.thecrag.com/en/climbing/hong-kong/tung-lung-chau" },
    { id: 11, typeCode: 'NC', lat: 22.345, lng: 114.165, diff: "F2B - F8B", grades: { rope: { min: "F2B", max: "F8B" } }, name: { zh: "畢架山", en: "Beacon Hill" }, desc: { zh: "花崗岩表面粗糙，擁有超過60條路線。", en: "Rough granite surface with over 60 routes." }, trans: { zh: "石硤尾轉乘32M小巴", en: "Minibus 32M from Shek Kip Mei" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.345,114.165", source: "https://www.thecrag.com/en/climbing/hong-kong/kowloon/area/825492426" },
    { id: 12, typeCode: 'NC', lat: 22.352, lng: 114.185, diff: "F5 - F7C+", grades: { rope: { min: "F5", max: "F7C+" } }, name: { zh: "獅子山", en: "Lion Rock" }, desc: { zh: "經典多繩距路線「鬼佬」是必爬路線，可俯瞰維港。", en: "Classic multi-pitch 'Gweilo' overlooking Victoria Harbour." }, trans: { zh: "慈雲山徒步上山", en: "Hike up from Tsz Wan Shan" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.352,114.185", source: "https://www.thecrag.com/12484579" },
    { id: 13, typeCode: 'NC', lat: 22.272, lng: 114.155, diff: "F4 - F7B", grades: { rope: { min: "F4", max: "F7B" } }, name: { zh: "中環岩壁", en: "Central Crags" }, desc: { zh: "約109條路線，在摩天大廈簇擁下享受攀岩。", en: "Around 109 routes nestled among skyscrapers." }, trans: { zh: "半山區", en: "Mid-Levels" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.272,114.155", source: "https://hongkongclimbing.com/routes/hong-kong/central-crags/" },

    // --- Gym climbing (AC) ---
    { id: 14, typeCode: 'AC', lat: 22.321, lng: 114.195, diff: "Top Rope/Lead", grades: null, name: { zh: "JUST CLIMB (啟德)", en: "JUST CLIMB (Kai Tak)" }, desc: { zh: "全港唯一有蓋綜合攀石場。17.5米先鋒牆。", en: "HK's only covered complex. 17.5m lead wall." }, trans: { zh: "啟德體育大道", en: "Kai Tak Sports Avenue" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.321,114.195", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 15, typeCode: 'AC', lat: 22.320, lng: 114.160, diff: "Top Rope", grades: null, name: { zh: "大角咀體育館", en: "Tai Kok Tsui Sports Centre" }, desc: { zh: "共設10條路線(高9米)。需持二級運動攀登證書。", en: "10 routes (9m). Level 2 climbing cert required." }, trans: { zh: "大角咀福全街", en: "Fuk Tsun Street, Tai Kok Tsui" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.320,114.160", source: null },

    // --- Outdoor bouldering (NB) - new additions ---
    { id: 16, typeCode: 'NB', lat: 22.214, lng: 114.214, diff: "V0 - V7", grades: { boulder: { min: "V0", max: "V7" } }, name: { zh: "赤柱抱石", en: "Stanley Blocs" }, desc: { zh: "赤柱一帶的花崗岩抱石區，多條路線散佈於山徑旁。", en: "Granite boulders scattered along trails near Stanley." }, trans: { zh: "中環乘巴士至赤柱", en: "Bus from Central to Stanley" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.214,114.214", source: "https://hongkongclimbing.com/blocs/stanley/" },
    { id: 17, typeCode: 'NB', lat: 22.405, lng: 114.123, diff: "V0 - V10", grades: { boulder: { min: "V0", max: "V10" } }, name: { zh: "大帽山抱石", en: "Tai Mo Shan Boulders" }, desc: { zh: "香港最高峰大帽山一帶的花崗岩抱石，路線分佈廣闊。", en: "Granite bouldering around Tai Mo Shan, Hong Kong's highest peak." }, trans: { zh: "荃灣乘巴士至大帽山郊野公園", en: "Bus from Tsuen Wan to Tai Mo Shan Country Park" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.405,114.123", source: "https://www.thecrag.com/en/climbing/hong-kong/new-territories/area/3808678353" },
    { id: 18, typeCode: 'NB', lat: 22.380, lng: 114.105, diff: "V0 - V9", grades: { boulder: { min: "V0", max: "V9" } }, name: { zh: "荃灣抱石", en: "Tsuen Wan Boulders" }, desc: { zh: "荃灣周邊多個花崗岩抱石點，包括下花山與蓮花山一帶。", en: "Several granite bouldering sectors around Tsuen Wan, including Ha Fa Shan and Lin Fa Shan." }, trans: { zh: "荃灣乘小巴上山", en: "Minibus from Tsuen Wan uphill" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.380,114.105", source: "https://www.thecrag.com/en/climbing/hong-kong/tsuen-wan-boulders" },
    { id: 19, typeCode: 'NB', lat: 22.305, lng: 114.272, diff: "V0 - V8", grades: { boulder: { min: "V0", max: "V8" } }, name: { zh: "銀線灣抱石", en: "Silver Bay Blocs" }, desc: { zh: "清水灣半島銀線灣一帶的海邊抱石，岩石粗糙。", en: "Rough seaside boulders near Silver Bay on Clear Water Bay Peninsula." }, trans: { zh: "坑口乘巴士至銀線灣", en: "Bus from Hang Hau to Silver Bay" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.305,114.272", source: "https://hongkongclimbing.com/silver-bay-blocs/" },
    { id: 20, typeCode: 'NB', lat: 22.200, lng: 114.030, diff: "V0 - V6", grades: { boulder: { min: "V0", max: "V6" } }, name: { zh: "長洲抱石", en: "Cheung Chau Blocs" }, desc: { zh: "長洲島上的花崗岩抱石區，路線多沿海邊散佈。", en: "Granite bouldering scattered around the coast of Cheung Chau island." }, trans: { zh: "中環碼頭乘渡輪至長洲", en: "Ferry from Central Pier to Cheung Chau" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.200,114.030", source: "https://hongkongclimbing.com/cheung-chau/" },
    { id: 21, typeCode: 'NB', lat: 22.410, lng: 114.240, diff: "V0 - V8", grades: { boulder: { min: "V0", max: "V8" } }, name: { zh: "馬鞍山抱石", en: "Ma On Shan Bouldering" }, desc: { zh: "馬鞍山一帶的天然抱石區，岩石質地良好。", en: "Natural bouldering sectors around Ma On Shan with good rock quality." }, trans: { zh: "馬鞍山乘巴士或徒步", en: "Bus or hike from Ma On Shan" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.410,114.240", source: "https://hongkongclimbing.com/blocs/ma-on-shan-bouldering/" },

    // --- Outdoor climbing (NC) - new additions ---
    { id: 22, typeCode: 'NC', lat: 22.256, lng: 114.250, diff: "F5A - F7B", grades: { rope: { min: "F5A", max: "F7B" } }, name: { zh: "哥連臣角", en: "Cape Collinson" }, desc: { zh: "港島東南端的海崖攀登區，以傳統攀登路線為主。", en: "Sea cliff climbing at the southeastern tip of Hong Kong Island, mostly trad routes." }, trans: { zh: "柴灣乘小巴至哥連臣角", en: "Minibus from Chai Wan to Cape Collinson" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.256,114.250", source: "https://www.thecrag.com/en/climbing/hong-kong/hong-kong-island/area/12484963" },
    { id: 23, typeCode: 'NC', lat: 22.295, lng: 114.244, diff: "F5A - F7A", grades: { rope: { min: "F5A", max: "F7A" } }, name: { zh: "魔鬼山", en: "Devil's Peak" }, desc: { zh: "九龍東魔鬼山的岩壁，俯瞰鯉魚門海峽。", en: "Crags on Devil's Peak overlooking Lei Yue Mun channel." }, trans: { zh: "油塘徒步上山", en: "Hike up from Yau Tong" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.295,114.244", source: "https://www.thecrag.com/en/climbing/hong-kong/kowloon/area/12484627" },
    { id: 24, typeCode: 'NC', lat: 22.267, lng: 114.219, diff: "F5A - F7B", grades: { rope: { min: "F5A", max: "F7B" } }, name: { zh: "柏架山", en: "Mount Parker Crags" }, desc: { zh: "柏架山一帶的多處岩壁，路線以運動攀登為主。", en: "Multiple crags around Mount Parker, mostly sport climbing." }, trans: { zh: "鰂魚涌徒步上山", en: "Hike up from Quarry Bay" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.267,114.219", source: "https://www.thecrag.com/en/climbing/hong-kong/hong-kong-island/area/2981853918" },
    { id: 25, typeCode: 'NC', lat: 22.290, lng: 114.290, diff: "F4 - F7B", grades: { rope: { min: "F4", max: "F7B" } }, name: { zh: "清水灣", en: "Clear Water Bay" }, desc: { zh: "清水灣半島的海崖與岩壁攀登區。", en: "Sea cliffs and crags on Clear Water Bay Peninsula." }, trans: { zh: "坑口乘巴士至清水灣", en: "Bus from Hang Hau to Clear Water Bay" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.290,114.290", source: "https://hongkongclimbing.com/routes/new-territories/clear-water-bay/" },
    { id: 26, typeCode: 'NC', lat: 22.240, lng: 114.148, diff: "F4 - F7A", grades: { rope: { min: "F4", max: "F7A" } }, name: { zh: "鴨脷洲", en: "Ap Lei Chau" }, desc: { zh: "鴨脷洲島上的岩壁攀登區，交通便利。", en: "Crags on Ap Lei Chau island with easy access." }, trans: { zh: "港鐵利東站步行", en: "MTR to Lei Tung station, then walk" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.240,114.148", source: "https://hongkongclimbing.com/routes/hong-kong/ap-lei-chau/ap-lei-chau-crags/" },
    { id: 27, typeCode: 'NC', lat: 22.344, lng: 114.219, diff: "F4 - F8A", grades: { rope: { min: "F4", max: "F8A" } }, name: { zh: "飛鵝山", en: "Kowloon Peak (Fei Ngo Shan)" }, desc: { zh: "飛鵝山的岩壁與抱石區，俯瞰九龍與港島。", en: "Crags and boulders on Fei Ngo Shan overlooking Kowloon and the island." }, trans: { zh: "彩虹乘小巴上山", en: "Minibus from Choi Hung uphill" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.344,114.219", source: "https://www.thecrag.com/en/climbing/hong-kong/kowloon/area/12484603" },
    { id: 28, typeCode: 'NC', lat: 22.167, lng: 114.260, diff: "F5A - F7B", grades: { rope: { min: "F5A", max: "F7B" } }, name: { zh: "蒲台島", en: "Po Toi" }, desc: { zh: "蒲台島的花崗岩海崖攀登區，位處香港南端。", en: "Granite sea cliff climbing on Po Toi, one of Hong Kong's southernmost spots." }, trans: { zh: "香港仔或赤柱乘街渡", en: "Ferry from Aberdeen or Stanley" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.167,114.260", source: "https://hongkongclimbing.com/routes/po-toi/" },
    { id: 29, typeCode: 'NC', lat: 22.207, lng: 114.256, diff: "F5A - F7A", grades: { rope: { min: "F5A", max: "F7A" } }, name: { zh: "鶴咀海崖", en: "Cape D'Aguilar" }, desc: { zh: "鶴咀半島東南端的海崖攀登區。", en: "Sea cliff climbing at the southeastern tip of Cape D'Aguilar." }, trans: { zh: "石澳乘巴士至鶴咀", en: "Bus from Shek O to Cape D'Aguilar" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.207,114.256", source: "https://hongkongclimbing.com/cape-daguilar/" },

    // --- Gym bouldering (AB) - new additions ---
    { id: 30, typeCode: 'AB', lat: 22.249, lng: 114.169, diff: "N/A", grades: null, name: { zh: "Attic V 攀石中心 (黃竹坑)", en: "Attic V (Wong Chuk Hang)" }, desc: { zh: "黃竹坑的室內抱石館。", en: "Indoor bouldering gym in Wong Chuk Hang." }, trans: { zh: "港鐵黃竹坑站", en: "MTR Wong Chuk Hang station" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.249,114.169", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 31, typeCode: 'AB', lat: 22.380, lng: 114.190, diff: "N/A", grades: null, name: { zh: "Camp Four Bouldering (沙田)", en: "Camp Four Bouldering (Shatin)" }, desc: { zh: "沙田的室內抱石館。", en: "Indoor bouldering gym in Shatin." }, trans: { zh: "沙田", en: "Shatin" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.380,114.190", source: "https://hongkongclimbing.com/climbing-walls/" },
    { id: 32, typeCode: 'AB', lat: 22.320, lng: 114.212, diff: "N/A", grades: null, name: { zh: "Project Climb & Boulder (九龍灣)", en: "Project Climb & Boulder (Kowloon Bay)" }, desc: { zh: "九龍灣的室內抱石館。", en: "Indoor bouldering gym in Kowloon Bay." }, trans: { zh: "九龍灣", en: "Kowloon Bay" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.320,114.212", source: "https://hongkongclimbing.com/climbing-walls/" },

    // --- Gym climbing (AC) - new additions ---
    { id: 33, typeCode: 'AC', lat: 22.312, lng: 114.173, diff: "Top Rope/Lead", grades: null, name: { zh: "YMCA Kings Park 攀石牆", en: "YMCA Kings Park Climbing Wall" }, desc: { zh: "京士柏青年會的高牆，設先鋒攀登牆。", en: "Tall walls at YMCA Kings Park with lead climbing." }, trans: { zh: "港鐵佐敦站", en: "MTR Jordan station" }, gmap: "https://www.google.com/maps/search/?api=1&query=22.312,114.173", source: "https://hongkongclimbing.com/climbing-walls/" }
  ];

  // Generate the display string from structured grades (null when no grades).
  function formatGrade(grades) {
    if (!grades) return null;
    if (grades.boulder) return grades.boulder.min + ' - ' + grades.boulder.max;
    if (grades.rope) return grades.rope.min + ' - ' + grades.rope.max;
    return null;
  }

  // Display string for a spot: generated from grades, or the raw diff fallback.
  function gradeText(spot) {
    var formatted = formatGrade(spot && spot.grades);
    return formatted !== null && formatted !== undefined ? formatted : ((spot && spot.diff) || '');
  }

  return { spots: spots, formatGrade: formatGrade, gradeText: gradeText };
});